config/routes.rb
Rails.application.routes.draw do

  resources :walks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/models/walk.rb
class Walk < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: %i[ show edit update destroy ]

  # GET /dogs or /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1 or /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs or /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: "Dog was successfully created." }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1 or /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: "Dog was successfully updated." }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1 or /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: "Dog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dog_params
      params.require(:dog).permit(:name)
    end
end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
  before_action :set_walk, only: %i[ show edit update destroy ]

  # GET /walks or /walks.json
  def index
    @walks = Walk.all
  end

  # GET /walks/1 or /walks/1.json
  def show
  end

  # GET /walks/new
  def new
    @walk = Walk.new
  end

  # GET /walks/1/edit
  def edit
  end

  # POST /walks or /walks.json
  def create
    @walk = Walk.new(walk_params)

    respond_to do |format|
      if @walk.save
        format.html { redirect_to @walk, notice: "Walk was successfully created." }
        format.json { render :show, status: :created, location: @walk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @walk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walks/1 or /walks/1.json
  def update
    respond_to do |format|
      if @walk.update(walk_params)
        format.html { redirect_to @walk, notice: "Walk was successfully updated." }
        format.json { render :show, status: :ok, location: @walk }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @walk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walks/1 or /walks/1.json
  def destroy
    @walk.destroy
    respond_to do |format|
      format.html { redirect_to walks_url, notice: "Walk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_walk
      @walk = Walk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def walk_params
      params.require(:walk).permit(:date, :time_of_walk, :walk_time_length, :pee, :pee_count, :poop, :poop_count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/dogwalkdata_helper.rb
module DogwalkdataHelper
end

app/helpers/walkdata_helper.rb
module WalkdataHelper
end

app/helpers/walks_helper.rb
module WalksHelper
end

app/views/dogs/_form.html.erb
<%= form_with(model: dog, local: true) do |form| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
        <% dog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogWalkTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/walks/_form.html.erb
<%= form_with(model: walk, local: true) do |form| %>
  <% if walk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(walk.errors.count, "error") %> prohibited this walk from being saved:</h2>

      <ul>
        <% walk.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :time_of_walk %>
    <%= form.time_select :time_of_walk %>
  </div>

  <div class="field">
    <%= form.label :walk_time_length %>
    <%= form.number_field :walk_time_length %>
  </div>

  <div class="field">
    <%= form.label :pee %>
    <%= form.check_box :pee %>
  </div>

  <div class="field">
    <%= form.label :pee_count %>
    <%= form.number_field :pee_count %>
  </div>

  <div class="field">
    <%= form.label :poop %>
    <%= form.check_box :poop %>
  </div>

  <div class="field">
    <%= form.label :poop_count %>
    <%= form.number_field :poop_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/walks/edit.html.erb
<h1>Editing Walk</h1>

<%= render 'form', walk: @walk %>

<%= link_to 'Show', @walk %> |
<%= link_to 'Back', walks_path %>

app/views/walks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Walks</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time of walk</th>
      <th>Walk time length</th>
      <th>Pee</th>
      <th>Pee count</th>
      <th>Poop</th>
      <th>Poop count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @walks.each do |walk| %>
      <tr>
        <td><%= walk.date %></td>
        <td><%= walk.time_of_walk %></td>
        <td><%= walk.walk_time_length %></td>
        <td><%= walk.pee %></td>
        <td><%= walk.pee_count %></td>
        <td><%= walk.poop %></td>
        <td><%= walk.poop_count %></td>
        <td><%= link_to 'Show', walk %></td>
        <td><%= link_to 'Edit', edit_walk_path(walk) %></td>
        <td><%= link_to 'Destroy', walk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Walk', new_walk_path %>

app/views/walks/new.html.erb
<h1>New Walk</h1>

<%= render 'form', walk: @walk %>

<%= link_to 'Back', walks_path %>

app/views/walks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @walk.date %>
</p>

<p>
  <strong>Time of walk:</strong>
  <%= @walk.time_of_walk %>
</p>

<p>
  <strong>Walk time length:</strong>
  <%= @walk.walk_time_length %>
</p>

<p>
  <strong>Pee:</strong>
  <%= @walk.pee %>
</p>

<p>
  <strong>Pee count:</strong>
  <%= @walk.pee_count %>
</p>

<p>
  <strong>Poop:</strong>
  <%= @walk.poop %>
</p>

<p>
  <strong>Poop count:</strong>
  <%= @walk.poop_count %>
</p>

<%= link_to 'Edit', edit_walk_path(@walk) %> |
<%= link_to 'Back', walks_path %>